from django.urls import path

from AdminApp.views import *

urlpatterns = [
    path('', admin),
    path('get_user_form/<id>/', get_user_form),
    path('user/add/', add_user),
    path('get_category/<_id>/', get_category),
    path('get_user/<id>/', get_user),
    path('delete_user/', delete_user),
    path('category/', list_category),
    path('category/<category_id>/all/', list_good),
    path('category/delete/<_id>/', delete_category),
    path('category/add/', add_category),
    path('category/edit/<_id>/', edit_category),
    path('good/', list_good),
    path('good/delete/<_id>/', delete_good),
    path('good/add/', add_good),
    path('good/edit/<_id>/', edit_good),
    path('get_good/<_id>/', get_good),
    path('menu/', list_menu),
    path('menu/delete/<_id>/', delete_menu),
    path('menu/add/', add_menu),
    path('menu/edit/<_id>/', edit_menu),
    path('get_menu/<_id>/', get_menu),
    path('album/', list_album),
    path('album/delete/<_id>/', delete_album),
    path('album/add/', add_album),
    path('album/edit/<_id>/', edit_album),
    path('get_album/<_id>/', get_album),
    path('image/delete/', delete_image),
    path('upload/<_id>/', upload),
    path('price/', list_price),
    path('price/delete/<_id>/', delete_price),
    path('price/add/', add_price),
    path('price/edit/<_id>/', edit_price),
    path('get_price/<_id>/', get_price),
    path('news/', list_news),
    path('news/delete/<_id>/', delete_news),
    path('news/add/', add_news),
    path('news/edit/<_id>/', edit_news),
    path('get_news/<_id>/', get_news),
    path('about/', list_organization),
    path('about/delete/<_id>/', delete_organization),
    path('about/add/', add_news),
    path('about/edit/<_id>/', edit_organization),
    path('get_organization/<_id>/', get_organization),
]
