# Generated by Django 2.1 on 2018-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
