# Generated by Django 2.1 on 2018-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
