# Generated by Django 2.1 on 2018-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180914_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='footer_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='footer_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
