# Generated by Django 2.1 on 2018-09-21 04:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_category_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='sub_desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
