# Generated by Django 2.1 on 2018-09-21 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180921_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='good',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Good'),
        ),
    ]
