# Generated by Django 2.1 on 2018-09-24 04:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180921_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=tinymce.models.HTMLField(default='test', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sub_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
