# Generated by Django 2.1 on 2018-09-24 04:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180924_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
