# Generated by Django 2.1 on 2018-09-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20180924_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_related_+', to='mainapp.Category', verbose_name='Сопутствующие категории'),
        ),
    ]
