# Generated by Django 2.1 on 2018-09-24 06:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180924_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='related',
        ),
        migrations.AddField(
            model_name='category',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category', verbose_name='Сопутствующие категории'),
        ),
    ]
