# Generated by Django 2.1 on 2018-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20180924_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='related',
        ),
        migrations.AddField(
            model_name='category',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_related_+', to='mainapp.Category', verbose_name='Сопутствующие категории'),
        ),
    ]
