# Generated by Django 2.1 on 2018-09-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20180928_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='good',
            name='active',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активен'),
        ),
    ]
