# Generated by Django 2.1 on 2018-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20180928_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sub_desc',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активна'),
        ),
        migrations.RemoveField(
            model_name='good',
            name='related',
        ),
        migrations.AddField(
            model_name='good',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_good_related_+', to='mainapp.Good', verbose_name='Сопутствующие товары'),
        ),
    ]
