# Generated by Django 2.1 on 2018-09-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20180928_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
