# Generated by Django 2.1 on 2018-09-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_good_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_category_related_+', to='mainapp.Category', verbose_name='Сопутствующие категории'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_good_related_+', to='mainapp.Good', verbose_name='Сопутствующие товары'),
        ),
    ]
