# Generated by Django 2.1 on 2018-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20180928_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='good', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='system',
            field=models.BooleanField(default=False, verbose_name='Системное'),
        ),
    ]
