# Generated by Django 2.1 on 2018-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20180928_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименовение')),
                ('desc', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='album', verbose_name='Изображение')),
                ('desc', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименовение')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PhotoAlbum', verbose_name='Альбом')),
            ],
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
    ]
