# Generated by Django 2.1 on 2018-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20181001_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photoimage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
