# Generated by Django 2.1 on 2018-10-08 06:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20181002_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименовение')),
                ('desc', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('map', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на карту')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('position', models.CharField(blank=True, max_length=64, null=True, verbose_name='Должность')),
            ],
        ),
    ]
