# Generated by Django 2.1 on 2018-10-12 08:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_photoalbum_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='main_page_desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст внизу на главной странице'),
        ),
    ]
